"""
causal_consequence.py — Action-Centred Consequence Estimation
=============================================================

Delayed observations can make a current state/action correlate with costs
generated by earlier actions.  This module estimates an action-centred contrast
that can help separate state risk from action-specific risk.

IMPLEMENTATION:

  We estimate an action-centred consequence contrast using a network that learns:
    1. E[C | s_t, a_t, h_t]         — total consequence given current obs
    2. E_a'[C | s_t, a', h_t]       — same-state action baseline
    3. ΔC(s, a, h) = (1) - (2)      — marginal attribution

  Holding both state and history fixed is essential: subtracting E[C|h] alone
  confounds state risk with action effect. The contrast is causal only when it
  is learned from interventional/randomised data or SCM labels; observational
  training by itself does not identify a do-effect.

The repository's six-dimensional simulator supplies controlled SCM labels, so
the contrast has a causal interpretation there.  On unsupported/real tasks the
same network is only an observational consequence model.  No convergence or
constraint-satisfaction theorem follows from this estimator alone.
"""

import numpy as np
try:
    from .networks import Adam, Linear, MLP, sigmoid, softplus
except ImportError:
    from networks import Adam, Linear, MLP, sigmoid, softplus



class CausalHistoryEncoder:
    """
    Deterministic recency-weighted summary of recent state/action/cost tuples.

    The previous GRU/projection parameters were never included in any backward
    pass, leaving a fixed random context while documentation called it learned.
    A deterministic summary is preferable until an end-to-end sequence
    gradient is implemented.
    """

    def __init__(self, state_dim: int, action_dim: int, hidden_dim: int = 32,
                 history_len: int = 8, lr: float = 3e-4, seed: int = 42):
        del lr, seed
        self.hidden_dim  = hidden_dim
        self.history_len = history_len
        self.action_dim  = action_dim
        self.state_dim   = state_dim

        self._history: list = []
        self._h = np.zeros((1, hidden_dim), np.float32)

    def push(self, state: np.ndarray, action: int, consequence: float):
        """Add a (s, a, c) tuple to the history buffer."""
        self._history.append((
            np.asarray(state, np.float32).copy(),
            int(action),
            float(consequence)
        ))
        if len(self._history) > self.history_len:
            self._history.pop(0)

    def _encode_history(self, history: list) -> np.ndarray:
        output = np.zeros(self.hidden_dim, np.float32)
        if not history:
            return output

        states = np.stack([np.asarray(item[0], np.float32) for item in history])
        actions = np.asarray([int(item[1]) for item in history], np.int32)
        costs = np.asarray([float(item[2]) for item in history], np.float32)
        weights = np.geomspace(0.5, 1.0, len(history), dtype=np.float32)
        weights /= weights.sum()

        scalar_slots = min(5, self.hidden_dim)
        remaining = self.hidden_dim - scalar_slots
        action_slots = min(self.action_dim, max(remaining // 3, 0))
        state_slots = remaining - action_slots

        cursor = 0
        if state_slots:
            state_mean = np.sum(
                np.clip(states[:, :state_slots], -5.0, 5.0)
                * weights[:, None], axis=0)
            output[:len(state_mean)] = state_mean
            cursor = len(state_mean)
        if action_slots:
            action_frequency = np.zeros(action_slots, np.float32)
            for action, weight in zip(actions, weights):
                if 0 <= action < action_slots:
                    action_frequency[action] += weight
            output[cursor:cursor + action_slots] = action_frequency
            cursor += action_slots

        summaries = np.asarray([
            np.dot(weights, costs), costs[-1], costs.max(), costs.std(),
            len(history) / max(self.history_len, 1),
        ], np.float32)
        available = self.hidden_dim - cursor
        count = min(available, len(summaries))
        output[cursor:cursor + count] = np.clip(
            summaries[:count], -10.0, 10.0)
        return output

    def context(self) -> np.ndarray:
        """
        Summarise the current online history.
        Returns (hidden_dim,) — the baseline consequence representation.
        """
        out = self._encode_history(self._history)
        self._h = out[None]
        return out

    def context_batch(self, histories: list) -> np.ndarray:
        """
        Encode a batch of histories (from replay buffer).
        histories: list of lists of (state, action, consequence) tuples.
        Returns (B, hidden_dim).
        """
        if not histories:
            return np.zeros((0, self.hidden_dim), np.float32)
        return np.stack([self._encode_history(history) for history in histories])

    def reset(self):
        """Clear history at episode start."""
        self._history.clear()
        self._h = np.zeros((1, self.hidden_dim), np.float32)

    def params(self):
        return []



class InterventionalConsequenceNet:
    """
    Estimates an action-centred consequence contrast:

        ΔC(s, a, h) = E[C | s, a, h] - E_a'[C | s, a', h]

    Two heads share a causal context encoder:
      1. total_head(s, a, h)  → E[C | s, a, h]   — total consequence
      2. base_head(s, h)      → E_a'[C | s,a',h]  — same-state baseline

    With balanced interventional/SCM labels, the difference is the same-state
    action effect relative to the chosen action baseline.  With observational
    policy data, it is only a conditional contrast.

    Training:
      - total_head trained on observed (s, a, c) tuples
      - base_head uses explicit same-state baseline labels when the synthetic
        SCM provides them; otherwise it learns a policy-weighted baseline
    """

    def __init__(self, state_dim: int, action_dim: int,
                 causal_dim: int = 32,
                 hidden_dim: int = 64,
                 n_layers:   int = 2,
                 history_len: int = 8,
                 lr: float = 4e-4,
                 seed: int = 42):
        rng = np.random.default_rng(seed)
        self.action_dim  = action_dim
        self.state_dim   = state_dim
        self.history_len = history_len
        self.causal_dim  = causal_dim

        self.encoder = CausalHistoryEncoder(
            state_dim, action_dim, causal_dim, history_len, lr, seed)

        total_inp = state_dim + action_dim + causal_dim
        self.total_trunk = MLP(
            [total_inp] + [hidden_dim]*n_layers, rng)
        self.total_head  = Linear(hidden_dim, 1, rng, scale=0.01)

        self.base_trunk = MLP(
            [state_dim + causal_dim] + [hidden_dim]*n_layers, rng)
        self.base_head  = Linear(hidden_dim, 1, rng, scale=0.01)

        self.sigma_head = Linear(hidden_dim, 1, rng, scale=0.01)

        total_p = (self.total_trunk.all_params() + self.total_head.params()
                   + self.sigma_head.params())
        base_p  = (self.base_trunk.all_params()  + self.base_head.params())
        self.optim      = Adam(total_p, lr=lr)
        self.base_optim = Adam(base_p,  lr=lr * 2.0)

    def _forward_total(self, states, actions, causal_ctx):
        """Forward pass for total consequence head. Returns raw pre-softplus logits for backprop."""
        oh = np.eye(self.action_dim, dtype=np.float32)[actions.astype(int)]
        x  = np.concatenate([
            np.asarray(states, np.float32), oh, causal_ctx], axis=-1)
        h         = self.total_trunk.forward(x)
        raw_C     = self.total_head.forward(h)
        raw_sigma = self.sigma_head.forward(h)
        C     = softplus(raw_C).squeeze(-1)
        sigma = softplus(raw_sigma).squeeze(-1) + 1e-4
        return C, sigma, h, raw_C, raw_sigma

    def _forward_base(self, states, causal_ctx):
        """Forward pass for E_a'[C | s, a', h]."""
        x = np.concatenate([
            np.asarray(states, np.float32),
            np.asarray(causal_ctx, np.float32),
        ], axis=-1)
        h     = self.base_trunk.forward(x)
        raw_B = self.base_head.forward(h)
        B     = softplus(raw_B).squeeze(-1)
        return B, h, raw_B

    def forward(self, states, actions, causal_ctx):
        """
        Returns:
          delta_C : (B,) — marginal causal attribution ΔC(s,a,h)
          C_total : (B,) — total expected consequence E[C|s,a,h]
          C_base  : (B,) — same-state action baseline E_a'[C|s,a',h]
          sigma   : (B,) — epistemic uncertainty
        """
        C_total, sigma, _, _, _ = self._forward_total(states, actions, causal_ctx)
        C_base,  _, _           = self._forward_base(states, causal_ctx)
        delta_C = C_total - C_base
        return delta_C, C_total, C_base, sigma

    def predict_delta(self, state: np.ndarray, actions: np.ndarray,
                       causal_ctx: np.ndarray) -> tuple:
        """
        Predict ΔC for all actions from a single state.
        state      : (state_dim,)
        actions    : (action_dim,) integer indices
        causal_ctx : (causal_dim,)  — from encoder.context()
        Returns delta_C (action_dim,), sigma (action_dim,)
        """
        B = len(actions)
        S = np.tile(state[None], (B, 1))
        ctx = np.tile(causal_ctx[None], (B, 1))
        delta_C, _, _, sigma = self.forward(S, actions, ctx)
        return delta_C.astype(np.float32), sigma.astype(np.float32)

    def update_step(self, states, actions, consequences,
                    causal_ctxs, weights, baseline_targets=None) -> dict:
        """
        Joint update of total_head and base_head.

        Loss = L_total + L_base + L_sigma
          L_total = weighted MSE of C_total vs observed c
          L_base  = weighted Huber loss of C_base vs same-state baseline target
          L_sigma = NLL under Laplace(C_total, sigma)

        Without explicit baseline labels, both heads use the same observed
        consequence and the base becomes policy-distribution dependent:
          total = f(s, a, h)  [full information]
          base  = g(s, h)     [action-marginal prediction]
        """
        tgt = np.asarray(consequences, np.float32)
        base_tgt = (tgt if baseline_targets is None else
                    np.asarray(baseline_targets, np.float32))
        if base_tgt.shape != tgt.shape:
            raise ValueError("baseline_targets must match consequences shape")
        ctx = np.asarray(causal_ctxs,  np.float32)
        W   = np.asarray(weights,       np.float32)
        if np.any(W < 0) or not np.all(np.isfinite(W)):
            raise ValueError("ICN weights must be finite and non-negative.")
        Wn = W / (W.sum() + 1e-8)

        C_total, sigma, h_total, raw_C, raw_sigma = self._forward_total(states, actions, ctx)
        C_base,  h_base, raw_B                    = self._forward_base(states, ctx)

        err_total = C_total - tgt
        l_total   = float(np.sum(Wn * err_total**2))

        err_base_raw = C_base - base_tgt
        delta_clip = 0.5
        abs_err_b  = np.abs(err_base_raw)
        err_base   = np.where(abs_err_b <= delta_clip,
                              err_base_raw,
                              delta_clip * np.sign(err_base_raw))
        base_loss  = np.where(abs_err_b <= delta_clip,
                              0.5 * err_base_raw**2,
                              delta_clip * (abs_err_b - 0.5 * delta_clip))
        l_base     = float(np.sum(Wn * base_loss))

        abs_err  = np.abs(C_total - tgt)
        l_sigma  = float(np.sum(
            Wn * (np.log(sigma + 1e-6) + abs_err / (sigma + 1e-6))))

        d_location_nll = Wn * np.sign(err_total) / (sigma + 1e-6)
        d_C_total_pre = ((2.0 * Wn * err_total + d_location_nll)
                         * sigmoid(raw_C.squeeze(-1)))
        d_total_h, dW_t, db_t = self.total_head.backward(d_C_total_pre[:, None])

        d_sigma       = Wn * (1.0 / (sigma + 1e-6)
                              - abs_err / (sigma + 1e-6) ** 2)
        d_sigma_pre   = d_sigma * sigmoid(raw_sigma.squeeze(-1))
        d_sigma_h, dW_s, db_s = self.sigma_head.backward(d_sigma_pre[:, None])

        d_trunk_total = d_total_h + d_sigma_h
        _, trunk_t_grads = self.total_trunk.backward(d_trunk_total)

        d_C_base_pre = (Wn * err_base
                        * sigmoid(raw_B.squeeze(-1)))
        d_base_h, dW_b, db_b = self.base_head.backward(d_C_base_pre[:, None])
        _, trunk_b_grads = self.base_trunk.backward(d_base_h)

        total_params = self.total_trunk.all_params() + self.total_head.params() + self.sigma_head.params()
        total_grads  = trunk_t_grads + [dW_t, db_t] + [dW_s, db_s]
        base_params  = self.base_trunk.all_params() + self.base_head.params()
        base_grads   = trunk_b_grads + [dW_b, db_b]
        if len(total_params) != len(total_grads):
            raise RuntimeError(
                f"ICN total grad mismatch: {len(total_params)} params vs "
                f"{len(total_grads)} grads")
        if len(base_params) != len(base_grads):
            raise RuntimeError(
                f"ICN base grad mismatch: {len(base_params)} params vs "
                f"{len(base_grads)} grads")
        self.optim.step(total_grads)
        self.base_optim.step(base_grads)

        return {
            "l_total": l_total,
            "l_base":  l_base,
            "l_sigma": l_sigma,
            "mean_delta_C": float(np.mean(np.abs(C_total - C_base))),
        }

    def _all_params(self):
        return (self.total_trunk.all_params() + self.total_head.params()
                + self.base_trunk.all_params()  + self.base_head.params()
                + self.sigma_head.params())


def d_softplus_vec(x):
    return sigmoid(x)



class CausalReplayBuffer:
    """
    Extended replay buffer that stores per-transition causal histories
    (the k most recent (s, a, c) tuples at the time of the transition).

    This is required because ΔC(s, a, h) depends on h, which varies
    across transitions — we can't recompute it at training time without
    storing the history.
    """

    def __init__(self, capacity: int = 60_000, history_len: int = 8,
                 state_dim: int = 6, action_dim: int = 5,
                 gru_dim: int = 40, seed: int = 42):
        if min(capacity, history_len, state_dim, action_dim, gru_dim) <= 0:
            raise ValueError("Replay dimensions and capacity must be positive")
        self.capacity    = capacity
        self.history_len = history_len
        self.state_dim   = state_dim
        self.action_dim  = action_dim
        self.gru_dim     = gru_dim
        self.rng         = np.random.default_rng(seed)

        self._states      = np.zeros((capacity, state_dim),  np.float32)
        self._actions     = np.zeros(capacity,               np.int32)
        self._rewards     = np.zeros(capacity,               np.float32)
        self._next_states = np.zeros((capacity, state_dim),  np.float32)
        self._consequences= np.zeros(capacity,               np.float32)
        self._aligned_consequences = np.zeros(capacity,       np.float32)
        self._aligned_valid = np.zeros(capacity,              np.bool_)
        self._scm_label_valid = np.zeros(capacity,            np.bool_)
        self._dones       = np.zeros(capacity,               np.float32)
        self._hiddens     = np.zeros((capacity, gru_dim),    np.float32)
        self._next_hid    = np.zeros((capacity, gru_dim),    np.float32)
        self._td_errors   = np.ones(capacity,                np.float32)
        self._c_errors    = np.ones(capacity,                np.float32)

        hist_dim = state_dim + action_dim + 1
        self._histories   = np.zeros((capacity, history_len, hist_dim), np.float32)
        self._history_valid = np.zeros((capacity, history_len), np.bool_)

        self._pos    = 0
        self._size   = 0
        self.alpha_p = 0.6
        self.beta_p  = 0.4
        self._beta_start   = 0.4
        self._beta_end     = 1.0
        self._beta_frames  = 100_000
        self._total_pushes = 0

    def push(self, state, action, reward, next_state, consequence,
             done, hidden, next_hidden, causal_history: list,
             scm_label_valid: bool = False):
        """
        causal_history: list of (state, action, consequence) tuples,
                        most recent k steps before this transition.
        """
        i = self._pos
        self._states[i]      = np.asarray(state, np.float32)
        self._actions[i]     = int(action)
        self._rewards[i]     = float(reward)
        self._next_states[i] = np.asarray(next_state, np.float32)
        self._consequences[i]= float(consequence)
        self._aligned_consequences[i] = 0.0
        self._aligned_valid[i] = False
        self._scm_label_valid[i] = bool(scm_label_valid)
        self._dones[i]       = float(done)
        self._hiddens[i]     = np.asarray(hidden,      np.float32).squeeze()
        self._next_hid[i]    = np.asarray(next_hidden, np.float32).squeeze()

        if self._size:
            self._td_errors[i] = max(float(self._td_errors[:self._size].max()), 1.0)
            self._c_errors[i] = max(float(self._c_errors[:self._size].max()), 1.0)
        else:
            self._td_errors[i] = 1.0
            self._c_errors[i] = 1.0

        hist_dim = self.state_dim + self.action_dim + 1
        oh_all   = np.eye(self.action_dim, dtype=np.float32)
        h_arr    = np.zeros((self.history_len, hist_dim), np.float32)
        h_valid  = np.zeros(self.history_len, np.bool_)
        for k, (s, a, c) in enumerate(causal_history[-self.history_len:]):
            action_index = int(a)
            if not 0 <= action_index < self.action_dim:
                raise ValueError(f"history action {action_index} is out of range")
            oh = oh_all[action_index]
            h_arr[k] = np.concatenate([
                np.asarray(s, np.float32), oh, [float(c)]])
            h_valid[k] = True
        self._histories[i] = h_arr
        self._history_valid[i] = h_valid

        self._pos  = (self._pos + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)
        self._total_pushes += 1
        frac = min(self._total_pushes / self._beta_frames, 1.0)
        self.beta_p = self._beta_start + frac * (self._beta_end - self._beta_start)
        return i

    def set_aligned_consequence(self, index: int, consequence: float):
        """Attach an observed consequence to its known source transition."""
        index = int(index)
        if not 0 <= index < self.capacity:
            raise IndexError("replay index outside buffer capacity")
        if index >= self._size and self._size < self.capacity:
            return False
        self._aligned_consequences[index] = float(consequence)
        self._aligned_valid[index] = True
        self._c_errors[index] = max(abs(float(consequence)), 1e-6)
        return True

    def _priorities(self):
        n   = self._size
        td  = np.clip(np.abs(self._td_errors[:n]), 1e-6, None)
        ce  = np.clip(np.abs(self._c_errors[:n]),  1e-6, None)
        td /= td.max(); ce /= ce.max()
        return (0.6 * td + 0.4 * ce) ** self.alpha_p

    def sample(self, batch_size: int):
        if self._size < batch_size:
            return None
        pri   = self._priorities()
        probs = pri / pri.sum()
        if batch_size == self._size:
            idxs = self.rng.permutation(self._size)
            W = np.ones(batch_size, np.float32)
        else:
            idxs = self.rng.choice(self._size, batch_size, replace=True, p=probs)
            W = (self._size * probs[idxs]) ** (-self.beta_p)
            W /= W.max()

        decoded_hists = []
        for i in idxs:
            hist = []
            for k in range(self.history_len):
                if not self._history_valid[i, k]:
                    continue
                row = self._histories[i, k]
                s  = row[:self.state_dim]
                oh = row[self.state_dim:self.state_dim + self.action_dim]
                c  = float(row[-1])
                a  = int(np.argmax(oh))
                hist.append((s, a, c))
            decoded_hists.append(hist)

        return {
            "states":       self._states[idxs],
            "actions":      self._actions[idxs],
            "rewards":      self._rewards[idxs],
            "next_states":  self._next_states[idxs],
            "consequences": self._consequences[idxs],
            "aligned_consequences": self._aligned_consequences[idxs],
            "aligned_valid": self._aligned_valid[idxs],
            "scm_label_valid": self._scm_label_valid[idxs],
            "dones":        self._dones[idxs],
            "hiddens":      self._hiddens[idxs],
            "next_hiddens": self._next_hid[idxs],
            "weights":      W.astype(np.float32),
            "indices":      idxs,
            "histories":    decoded_hists,
        }

    def update_priorities(self, indices, td_errors, c_errors=None):
        for k, i in enumerate(indices):
            if i < self._size:
                self._td_errors[i] = abs(float(td_errors[k])) + 1e-6
                if c_errors is not None:
                    self._c_errors[i] = abs(float(c_errors[k])) + 1e-6

    def ready_count(self): return self._size
    def __len__(self):     return self._size
